### ISSUE TITLE
problem at "python setup.py build develop"

### ISSUE THREAD

**Issue by GT9505** [facebookresearch/maskrcnn-benchmark#176]
I follow the INSTALL.md, but got a problem at last step like:

$ python setup.py build develop
running build
running build_py
running build_ext
Traceback (most recent call last):
  File "setup.py", line 68, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/mnt/lvdisk1/gongtao/software/Anaconda3-5.3.0/envs/maskrcnn_benchmark/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/mnt/lvdisk1/gongtao/software/Anaconda3-5.3.0/envs/maskrcnn_benchmark/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/mnt/lvdisk1/gongtao/software/Anaconda3-5.3.0/envs/maskrcnn_benchmark/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/mnt/lvdisk1/gongtao/software/Anaconda3-5.3.0/envs/maskrcnn_benchmark/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/mnt/lvdisk1/gongtao/software/Anaconda3-5.3.0/envs/maskrcnn_benchmark/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/mnt/lvdisk1/gongtao/software/Anaconda3-5.3.0/envs/maskrcnn_benchmark/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/mnt/lvdisk1/gongtao/software/Anaconda3-5.3.0/envs/maskrcnn_benchmark/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/mnt/lvdisk1/gongtao/software/Anaconda3-5.3.0/envs/maskrcnn_benchmark/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/mnt/lvdisk1/gongtao/software/Anaconda3-5.3.0/envs/maskrcnn_benchmark/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/mnt/lvdisk1/gongtao/software/Anaconda3-5.3.0/envs/maskrcnn_benchmark/lib/python3.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/mnt/lvdisk1/gongtao/software/Anaconda3-5.3.0/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 210, in build_extensions
    self._check_abi()
  File "/mnt/lvdisk1/gongtao/software/Anaconda3-5.3.0/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 333, in _check_abi
    check_compiler_abi_compatibility(compiler)
  File "/mnt/lvdisk1/gongtao/software/Anaconda3-5.3.0/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 188, in check_compiler_abi_compatibility
    compiler = '{} {}'.format(compiler, version.group(0))
AttributeError: 'list' object has no attribute 'group'

my environment is:
ubuntu 14.04
gcc version is 7.3.0
pytorch-nightly-gpu installed, version: 1.0.0.dev20181119
cuda 8.0
cudnn v5.1

Is this the reason of cuda and cudnn?
Thank you!

**Comment by thangvubk** [comment]
Your gcc version might be not compatible. I also have problems with gcc7 before. Pls check with gcc 5.4 to see if it helps.

**Comment by GT9505** [comment]
> Your gcc version might be not compatible. I also have problems with gcc7 before. Pls check with gcc 5.4 to see if it helps.

Yes. I change to gcc 4.9.4 and the problem is solved

**Comment by fmassa** [comment]
Hi,

I'm opening an issue in main PyTorch to keep them aware of this issue, which happens with PyTorch C++ extensions itself.

**Comment by zjhuang22** [comment]
I solve this problem by changing pytorch-nightly version 1.0.0.dev20181119 to 1.0.0.dev20181116

**Comment by fmassa** [comment]
@olgaliak I just opened a new issue in PyTorch to get this fixed https://github.com/pytorch/pytorch/issues/14502

The fix is pretty simple, and just requires removing the `.group()` I believe.

But you'll still have the warning due to ABI incompatibility

**Comment by fmassa** [comment]
This PR should fix it https://github.com/pytorch/pytorch/pull/14505

**Comment by fmassa** [comment]
Fixed in latest version of PyTorch
